apiVersion: v1
kind: Service
metadata:
  name: shopsphere-api-service
  namespace: shopsphere
spec:
  selector:
    app: shopsphere-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer