apiVersion: v1
kind: Service
metadata:
  name: shopsphere-client-service
  namespace: shopsphere
spec:
  selector:
    app: shopsphere-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer