apiVersion: v1
kind: Service
metadata:
  name: shopsphere-mongo
  namespace: shopsphere
spec:
  selector:
    app: shopsphere-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP