name: CI-CD - Build, Push to ECR

on:
  push:
    branches:
      - main
      - FeatureBranch
  pull_request:
    branches:
      - main
      - FeatureBranch
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 690640933457.dkr.ecr.eu-north-1.amazonaws.com
  ECR_REPOSITORY_API: shopsphere/api
  ECR_REPOSITORY_CLIENT: shopsphere/client
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build API image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG -f ShopSphere.API/Dockerfile .

      - name: Push API image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_API:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_API:latest

      - name: Build Client image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_CLIENT:$IMAGE_TAG -f ShopSphere.Client/Dockerfile ShopSphere.Client

      - name: Push Client image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_CLIENT:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY_CLIENT:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_CLIENT:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_CLIENT:latest